### ISSUE TITLE
Explainer for busy people please

### ISSUE THREAD

**Issue by MVSICA-FICTA** [maxkorolev/vue-rxjs#2]
Okay, nice to see more RxJS in Vueland. Its been a really long day, how about some up front rational for what makes vue-rxjs different (better?) than vue-rx. Thanks :)

**Comment by maxkorolev** [comment]
Documentation is on the way, I think I will finish it in several days

**Comment by maxkorolev** [comment]
I wrote README, if there is some questions, I will be happy to answer)
